### ISSUE TITLE
Trying to sort the grid throws and exception

### ISSUE THREAD

**Issue by pmalecka** [ameed/Ameed.XTBPlugins#2]
************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewColumnCollection.get_Item(Int32 index)
   at SearchPOALandscape.POAListControl.dgvShares_CellClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ameed** [comment]
Hi, can you mention which search you performed and which column you clicked? 
Thanks

**Comment by ameed** [comment]
Fixed with latest version 1.2017.5.16, please install most recent plugin from store
